version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: my-laravel-app:v1.0
        container_name: my-laravel-app
        restart: always
        expose:
            - 9000
        environment:
            - APP_KEY=${APP_KEY}
            - APP_ENV=production
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - REDIS_HOST=redis
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:latest
        container_name: my-laravel-nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
            - ./ssl:/etc/nginx/ssl
            - ./data/certbot/conf:/etc/letsencrypt # Volume untuk menyimpan sertifikat SSL
            - ./data/certbot/www:/var/www/certbot # Tempat penyimpanan webroot untuk verifikasi Certbot
        depends_on:
            - app
        command: ["nginx", "-g", "daemon off;"]

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; certbot renew; sleep 12h & wait'" # Pembaruan otomatis sertifikat
        depends_on:
            - nginx

    db:
        image: mysql:8.0
        container_name: my-laravel-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

    redis:
        image: redis:alpine
        container_name: my-laravel-redis
        restart: always

volumes:
    db-data:
        driver: local
