[build]
# Perintah instalasi yang akan mengunduh dependensi PHP dan Node.js
install_cmd = "composer install --no-dev --optimize-autoloader && npm install"

# Perintah build untuk mengkompilasi aset front-end
build_cmd = "npm run build"

[start]
# Perintah start untuk menjalankan server di produksi
start_cmd = "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf"
