name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main  # Deploy setiap kali ada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ambil seluruh commit history
        submodules: true

    - name: Install Node.js & Dependencies
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: npm install
    - run: npm run build

    - name: Rename .gitignore (Agar semua file di-upload)
      run: mv .gitignore .gitignore.bak

    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: ./
        server-dir: /

    - name: Restore .gitignore
      run: mv .gitignore.bak .gitignore
